/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FlightRecorderRouteImport } from './routes/flight-recorder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightRecorderRoute = FlightRecorderRouteImport.update({
  id: '/flight-recorder',
  path: '/flight-recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flight-recorder': typeof FlightRecorderRoute
  '/mcp': typeof McpRoute
  '/tools': typeof ToolsRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flight-recorder': typeof FlightRecorderRoute
  '/mcp': typeof McpRoute
  '/tools': typeof ToolsRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flight-recorder': typeof FlightRecorderRoute
  '/mcp': typeof McpRoute
  '/tools': typeof ToolsRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flight-recorder' | '/mcp' | '/tools' | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flight-recorder' | '/mcp' | '/tools' | '/api/$'
  id: '__root__' | '/' | '/flight-recorder' | '/mcp' | '/tools' | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlightRecorderRoute: typeof FlightRecorderRoute
  McpRoute: typeof McpRoute
  ToolsRoute: typeof ToolsRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-recorder': {
      id: '/flight-recorder'
      path: '/flight-recorder'
      fullPath: '/flight-recorder'
      preLoaderRoute: typeof FlightRecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlightRecorderRoute: FlightRecorderRoute,
  McpRoute: McpRoute,
  ToolsRoute: ToolsRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
